AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY: 
development:
  SENDGRID_USERNAME: 
  SENDGRID_PASSWORD: 
  AWS_BUCKET: first-bloccit-app-development
  FACEBOOK_ID:
  FACEBOOK_SECRET:
production:
  AWS_BUCKET: first-bloccit-app-production
  FACEBOOK_ID:
  FACEBOOK_SECRET: